
# ## With Loki
# server:
#   http_listen_port: 3100
#   grpc_listen_port: 9095
#   http_server_read_timeout: 30s
#   http_server_write_timeout: 30s
#   grpc_server_max_recv_msg_size: 104857600  # 100MB

# # Authentication
# auth_enabled: false

# # Limits and quotas
# limits_config:
#   allow_structured_metadata: true
#   volume_enabled: true
#   ingestion_rate_mb: 4
#   ingestion_burst_size_mb: 6
#   max_global_streams_per_user: 5000
#   max_query_length: 721h
#   max_query_parallelism: 32
#   retention_period: 744h

# # Common configurations
# common:
#   path_prefix: /tmp/loki
#   replication_factor: 1
#   ring:
#     kvstore:
#       store: consul
#       consul:
#         host: consul:8500
#         consistent_reads: true

# # Distributor configuration
# distributor:
#   ring:
#     kvstore:
#       store: consul
#       consul:
#         host: consul:8500
#         consistent_reads: true

# # Ingester configuration
# ingester:
#   lifecycler:
#     ring:
#       kvstore:
#         store: consul
#         consul:
#           host: consul:8500
#           consistent_reads: true
#     final_sleep: 0s
#   chunk_idle_period: 1h
#   chunk_retain_period: 30s
#   max_chunk_age: 2h
#   chunk_target_size: 1536000

# # Schema configuration
# schema_config:
#   configs:
#     - from: 2020-05-15
#       store: tsdb
#       object_store: filesystem
#       schema: v13
#       index:
#         prefix: index_
#         period: 24h

# # Storage configuration
# storage_config:
#   tsdb_shipper:
#     active_index_directory: /tmp/loki/index
#     cache_location: /tmp/loki/index_cache
#   filesystem:
#     directory: /tmp/loki/chunks

# # Query configuration
# query_range:
#   align_queries_with_step: true
#   max_retries: 5
#   cache_results: true
#   results_cache:
#     cache:
#       embedded_cache:
#         enabled: true
#         max_size_mb: 512
#         ttl: 24h

# # Pattern ingester configuration
# pattern_ingester:
#   enabled: true

# # Compactor configuration
# compactor:
#   working_directory: /tmp/loki/compactor
#   compaction_interval: 10m
#   retention_enabled: true
#   retention_delete_delay: 2h
#   retention_delete_worker_count: 150
#   delete_request_cancel_period: 24h
#   delete_request_store: filesystem

# # Table manager configuration
# table_manager:
#   retention_deletes_enabled: true
#   retention_period: 744h




# ```
# ### 
# # Server configuration
# server:
#   http_listen_port: 3100
#   grpc_listen_port: 9095
#   http_server_read_timeout: 30s
#   http_server_write_timeout: 30s
#   grpc_server_max_recv_msg_size: 104857600  # 100MB

# # Authentication
# auth_enabled: false

# # Limits and quotas
# limits_config:
#   allow_structured_metadata: true
#   volume_enabled: true
#   ingestion_rate_mb: 4
#   ingestion_burst_size_mb: 6
#   max_global_streams_per_user: 5000
#   max_query_length: 721h
#   max_query_parallelism: 32
#   retention_period: 744h

# # Common configurations
# common:
#   path_prefix: /tmp/loki
#   replication_factor: 1
#   ring:
#     instance_addr: 0.0.0.0
#     kvstore:
#       store: inmemory

# # Schema configuration
# schema_config:
#   configs:
#     - from: 2020-05-15
#       store: tsdb
#       object_store: filesystem
#       schema: v13
#       index:
#         prefix: index_
#         period: 24h

# # Storage configuration
# storage_config:
#   tsdb_shipper:
#     active_index_directory: /tmp/loki/index
#     cache_location: /tmp/loki/index_cache
#   filesystem:
#     directory: /tmp/loki/chunks

# # Query configuration
# query_range:
#   align_queries_with_step: true
#   max_retries: 5
#   cache_results: true
#   results_cache:
#     cache:
#       embedded_cache:
#         enabled: true
#         max_size_mb: 512
#         ttl: 24h

# # Ingester configuration
# ingester:
#   lifecycler:
#     ring:
#       replication_factor: 1
#       kvstore:
#         store: inmemory
#     final_sleep: 0s
#   chunk_idle_period: 1h
#   chunk_retain_period: 30s
#   max_chunk_age: 2h
#   chunk_target_size: 1536000

# # Pattern ingester configuration
# pattern_ingester:
#   enabled: true

# # Compactor configuration
# compactor:
#   working_directory: /tmp/loki/compactor
#   compaction_interval: 10m
#   retention_enabled: true
#   retention_delete_delay: 2h
#   retention_delete_worker_count: 150
#   delete_request_cancel_period: 24h
#   delete_request_store: filesystem

# # Table manager configuration
# table_manager:
#   retention_deletes_enabled: true
#   retention_period: 744h



# # Global settings for Loki
# auth_enabled: false

# server:
#   http_listen_port: 3100

# distributor:
#   ring:
#     kvstore:
#       store: memberlist

# ingester:
#   lifecycler:
#     ring:
#       kvstore:
#         store: memberlist
#       replication_factor: 1
#   chunk_idle_period: 15m
#   chunk_retain_period: 30s
#   max_transfer_retries: 20

# # Limits and validation configuration
# limits_config:
#   enforce_metric_name: false  # Remove this if unrecognized, or comment out if unsupported
#   allow_structured_metadata: false  # Temporary fix to disable structured metadata support

# schema_config:
#   configs:
#     - from: "2020-09-07"
#       store: tsdb  # Change to `tsdb` for schema v13 compatibility with structured metadata
#       object_store: filesystem  # Or change to `gcs` or `s3` based on your setup
#       schema: v13  # Ensure version is at least 13 for structured metadata support
#       index:
#         prefix: index_
#         period: 168h

# storage_config:
#   filesystem:
#     chunks_directory: /var/loki/chunks
#     rules_directory: /var/loki/rules

# compactor:
#   working_directory: /var/loki/compactor
#   shared_store: filesystem

# table_manager:
#   retention_deletes_enabled: true
#   retention_period: 24h

# query_range:
#   align_queries_with_step: true
#   max_retries: 5
#   split_queries_by_interval: 15m
#   cache_results: true
#   results_cache:
#     cache:
#       enable_fifocache: true
#       fifocache:
#         max_size: 1024

# ruler:
#   storage:
#     type: local
#   rule_path: /tmp/loki/rules-temp
#   alertmanager_url: http://localhost:9093








# This is a complete configuration to deploy Loki backed by the filesystem.
# The index will be shipped to the storage via tsdb-shipper.

auth_enabled: false

limits_config:
  allow_structured_metadata: true
  volume_enabled: true

server:
  http_listen_port: 3100

common:
  ring:
    instance_addr: 0.0.0.0
    kvstore:
      store: inmemory
  replication_factor: 1
  path_prefix: /tmp/loki

schema_config:
  configs:
  - from: 2020-05-15
    store: tsdb
    object_store: filesystem
    schema: v13
    index:
      prefix: index_
      period: 24h

storage_config:
  tsdb_shipper:
    active_index_directory: /tmp/loki/index
    cache_location: /tmp/loki/index_cache
  filesystem:
    directory: /tmp/loki/chunks

pattern_ingester:
  enabled: true