receivers:
  otlp:
    protocols:
      grpc:
        endpoint: otel-collector:4317
      http:
        endpoint: otel-collector:4318

processors:
  batch:
    timeout: 5s
    send_batch_size: 500
    send_batch_max_size: 2000

exporters:
  otlphttp/logs:
    endpoint: "${OTLP_HTTP_LOGS_ENDPOINT}"
    tls:
      insecure: true
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s
    sending_queue:
      enabled: true
      queue_size: 1000

  otlp/tempo:
    endpoint: "${OTLP_GRPC_TRACES_ENDPOINT}"
    tls:
      insecure: true
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s
    sending_queue:
      enabled: true
      queue_size: 1000

extensions:
  health_check:
    endpoint: 0.0.0.0:13133

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/tempo]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/logs]

  telemetry:
    logs:
      level: "info"
    metrics:
      level: "detailed"


# receivers:
#   otlp:
#     protocols:
#       grpc:
#         endpoint: 0.0.0.0:4317
#       http:
#         endpoint: 0.0.0.0:4318

# processors:
#   batch:
#     timeout: 1s
#     send_batch_size: 1024

# exporters:
#   otlphttp/logs:
#     endpoint: "http://loki:3100/otlp"
#     tls:
#       insecure: true
  
#   otlp/tempo:
#     endpoint: tempo:3200
#     tls:
#       insecure: true
  
# service:
#   pipelines:
#     traces:
#       receivers: [otlp]
#       processors: [batch]
#       exporters: [otlp/tempo]
#     logs:
#       receivers: [otlp]
#       processors: [batch]
#       exporters: [otlphttp/logs]

#   telemetry:
#     logs:
#       level: "info"
#     metrics:
#       level: "detailed"



##Working one 
# receivers:
#   otlp:
#     protocols:
#       grpc:
#         endpoint: 0.0.0.0:4317
#       http:
#         endpoint: 0.0.0.0:4318

# exporters:
#   otlphttp/logs:
#     endpoint: "http://loki:3100/otlp"
#     tls:
#       insecure: true

# service:
#   pipelines:
#     logs:
#       receivers: [otlp]
#       exporters: [otlphttp/logs]






## Best one
# receivers:
#   otlp:
#     protocols:
#       grpc:
#         endpoint: 0.0.0.0:4317
#       http:
#         endpoint: 0.0.0.0:4318

# exporters:
#   otlphttp/logs:
#     endpoint: "http://loki:3100/otlp"
#     tls:
#       insecure: true
#   otlp/traces:
#     endpoint: tempo:3200
#     tls:
#       insecure: true

# service:
#   pipelines:
#     logs:
#       receivers: [otlp]
#       exporters: [otlphttp/logs]
#     traces:
#       receivers: [otlp]
#       exporters: [otlp/traces]
